version: '3.3'
services:
  posts:
    build:
      context: ./src
      dockerfile: Dockerfile.posts
    expose:
      - 5000
    environment:
      - COMMENTS=comments
      - DBCONNECTIONSTRING=mongo
      - DBNAME=db
      - CACHECAPACITY=2
    depends_on:
      - mongo
    networks:
      - network
  
  comments:
    build:
      context: ./src
      dockerfile: Dockerfile.comments
    expose:
      - 5000
    environment:
      - POSTS=posts
      - DBCONNECTIONSTRING=mongo
      - DBNAME=db
      - CACHECAPACITY=2
    depends_on:
      - mongo
    networks:
      - network
  
  reverseproxy:
    build: 
      context: ./src/reverseproxy
    ports:
      - 5000:5000
    environment:
      - POSTS=posts
      - COMMENTS=comments
    depends_on:
      - posts
      - comments
    networks:
      - network

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=db
    volumes:
      - ./data:/data/db
    expose:
      - 27017
    networks:
      - network

networks:
  network:
